sasPatternDict = {"proc print":"proc print",
                  "proc sort":"proc sort",
                  "proc datasets":"proc datasets",
                  "proc +format":"proc format",
                  "proc +export":"proc export",
                  "proc +import":"proc import",
                  "\\bdata\\b":"data",
                  "run *;":"run;",
                  "quit *;":"quit;",
                  " noobs":" noobs",
                  "datalines":"datalines",
                  "libname ":"libname ",
                  "\\blibrary\\b":"library",
                  "value ":"value ",
                  "\\bid\\b":"id",
                  "\\bdelete\\b":"delete",
                  "datafile":"datafile",
                  "\\bretain":"retain",
                  "keep *=":"keep=",
                  "dbms *=":"dbms=",
                  "replace":"replace",
                  "scantime":"scantime",
                  "usedate":"usedate",
                  "data ":"data ",
                  "set ":"set ",
                  " then ":" then ",
                  "if ":"if ",
                  "else ":"else ",
                  "eof ":"eof ",
                  "output":"output",
                  "end":"end",
                  "format ":"format ",
                  "nodupkey":"nodupkey",
                  "\\bby\\b":"by",
                  "\\bvar\\b ":"var ",
                  "\\blabel\\b":"label",
                  "\\bmerge\\b":"merge",
                  "drop ":"drop",
                  "\\bwhere\\b":"where",
                  "title ":"title ",
                  "\\bdo\\b":"do",
                  "\\bto\\b":"to",
                  "\\binto\\b":"into",
                  "sum\(":"sum(",
                  "\\bmissing\\b":"missing",
                  "\\barray\\b":"array",
                  "where *=":"where=",
                  "\\bdrop\\b":"drop",
                  "drop *=":"drop=",
                  "\\brename\\b":"rename",
                  "rename *=":"rename=",
                  "year\(":"sum(",
                  "month\(":"month(",
                  "proc +freq *data *=":"proc freq data=",
                  "\\btables\\b":"tables",
                  "\\bnoprint\\b":"noprint",
                  "\\bretrain\\b":"noprint",
                  "mdy\(":"mdy(",
                  "\\btable\\b":"table",
                  "proc *sql":"proc sql",
                  "\\bselect\\b":"select",
                  "\\bfrom\\b":"from",
                  "\\bods\\b":"ods",
                  "\\brtf\\b":"rtf",
                  "proc +sgplot":"proc sgplot",
                  "xaxis":"xaxis",
                  "yaxis":"yaxis",
                  "\\bclose\\b":"close",
                  "proc +logistic":"proc logistic",
                  "odsfile":"odsfile",
                  "\\bfilename\\b":"filename",
                  "\\bfile\\b":"file",
                  "\\bdm\\b":"dm",
                  "dim\(":"dim(",
                  "first\.":"first.",
                  "last\.":"last.",
                  "_n_":"_n_",
                  "proc +transpose":"proc transpose",
                  "\\bdescending\\b":"descending",
                  "max\(":"max(",
                  "min\(":"min(",
                  "round\(":"round(",
                  "rannor\(":"rannor(",
                  "rand\(":"rand(",
                  "strip\(":"strip(",
                  "cat\(":"cat(",
                  "\\branks\\b":"ranks",
                  "proc +template ":"proc template",
                  "proc +contents +":"proc contents",
                  "\\binformat\\b":"informat",
                  "\\blength\\b":"length",
                  "length\(":"length(",
                  "\\bvarnum\\b":"varnum",
                  "proc +tabulate\\b":"proc tabulate",
                  "proc +report\\b":"proc report",
                  "\\bcolumn\\b":"column",
                  "\\bdefine\\b":"define",
                  "\\bput\\b":"put",
                  "\\botherwise\\b":"otherwise",
                  "%include":"%include",
                  "%let":"%let",
                  "%macro +":"%macro ",
                  "%mend +":"%mend ",
                  "%if +":"%if ",
                  "%then +":"%then ",
                  "%else +":"%else ",
                  "%do *;":"%do;",
                  "%end *;":"%end;",
                  "%put +":"%put ",
                  "%goto +":"%goto",
                  "%scan":"%scan",
                  "%str":"%str",
                  "%upcase":"%upcase",
                  "%symdel":"%symdel",
                  "intnx":"intnx",
                  "compress\(":"compress(",
                  "scan\(":"scan(",
                  "index\(":"index(",
                  "substr\(":"substr(",
                  "fileexist\(":"fileexist(",
                  "_temporary_":"_temporary_",
                  "\\bpad\\b":"pad",
                  "\\btruncover\\b":"truncover",
                  "\\bdsd\\b":"dsd",
                  "\\bmissover\\b":"missover",
                  "\\bwhile\\b":"while",
                  }
